[platformio]
default_envs = native

[env]
build_flags =
  -std=gnu++17
  -Wall
  -Wextra
  -Wpedantic

[env:native]
platform = native
build_flags =
  ${env.build_flags}
  -DDIXPAS_TARGET_NATIVE=1

[env:nanoevery]
platform = atmelmegaavr
board = nano_every
framework = arduino
build_flags =
  ${env.build_flags}
  -DDIXPAS_TARGET_ARDUINO=1
